# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c67ca8a5645796ba8c60437e1425caaff0e2515e8d8eb179e57c983b12458e19510b3e5d85f8a48eb6ae71df2eedc4ada7645f2d69d37349456a16ddfab846ca

test:
  secret_key_base: e4c69766c8b0c5d125552e8f9ef95afe527095b20586d434a70259c013b9824a3595a90c629f7eefd3d0dbb328d9eba94d0cf337884ede3f33fa00276a1ef93d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
